/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 21-Nov.-2023 10:33:29 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cierrecaja_Capital]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cierrecaja] DROP CONSTRAINT [FK_Cierrecaja_Capital]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Metodopago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Metodopago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detalleordencompra_Ordencompra]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detalleordencompra] DROP CONSTRAINT [FK_Detalleordencompra_Ordencompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detalleordencompra_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detalleordencompra] DROP CONSTRAINT [FK_Detalleordencompra_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallepedido_Venta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallepedido] DROP CONSTRAINT [FK_Detallepedido_Venta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Detallepedido_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Detallepedido] DROP CONSTRAINT [FK_Detallepedido_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordencompra_Formapago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordencompra] DROP CONSTRAINT [FK_Ordencompra_Formapago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordencompra_Requerimiento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordencompra] DROP CONSTRAINT [FK_Ordencompra_Requerimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordencompra_Proveedor]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordencompra] DROP CONSTRAINT [FK_Ordencompra_Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Categoria]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto] DROP CONSTRAINT [FK_Producto_Categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Proveedor_Ciudad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Proveedor] DROP CONSTRAINT [FK_Proveedor_Ciudad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Requerimiento_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Requerimiento] DROP CONSTRAINT [FK_Requerimiento_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Venta_Cierrecaja]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Venta] DROP CONSTRAINT [FK_Venta_Cierrecaja]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Venta_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Venta] DROP CONSTRAINT [FK_Venta_Cliente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Capital]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Capital]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Categoria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cierrecaja]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cierrecaja]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ciudad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ciudad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Detalleordencompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Detalleordencompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Detallepedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Detallepedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Formapago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Formapago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Metodopago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Metodopago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ordencompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ordencompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Proveedor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Requerimiento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Requerimiento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Venta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Venta]
GO

/* Create Tables */

CREATE TABLE [Capital]
(
	[CapitalID] int NOT NULL IDENTITY (1, 1),
	[Monto] nvarchar(50) NULL
)
GO

CREATE TABLE [Categoria]
(
	[CategoriaID] int NOT NULL IDENTITY (1, 1),
	[NombreCategoria] nvarchar(50) NULL,
	[Descripcion] nvarchar(50) NULL
)
GO

CREATE TABLE [Cierrecaja]
(
	[CierrecajaID] int NOT NULL IDENTITY (1, 1),
	[CapitalID] int NOT NULL,
	[GananciaTotal] real NULL,
	[TotalEgreso] real NULL,
	[TotalIngreso] real NULL
)
GO

CREATE TABLE [Ciudad]
(
	[CiudadID] int NOT NULL IDENTITY (1, 1),
	[Nombre] nvarchar(50) NULL
)
GO

CREATE TABLE [Cliente]
(
	[ClienteID] int NOT NULL IDENTITY (1, 1),
	[DNI] varchar(50) NULL,
	[MetodopagoID] int NOT NULL,
	[Nombre] nvarchar(max) NULL,
	[Direccion] nvarchar(max) NULL,
	[Telefono] nvarchar(max) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Detalleordencompra]
(
	[DetalleordencompraID] int NOT NULL IDENTITY (1, 1),
	[OrdencompraID] int NOT NULL,
	[ProductoID] int NOT NULL,
	[NombreProducto] nvarchar(50) NULL,
	[Categoria] nvarchar(50) NULL,
	[CostoUnitario] real NULL,
	[CantidadRequerida] int NULL
)
GO

CREATE TABLE [Detallepedido]
(
	[DetallepedidoID] int NOT NULL IDENTITY (1, 1),
	[VentaID] int NOT NULL,
	[ProductoID] int NOT NULL,
	[Nombre] nvarchar(50) NULL,
	[DescProducto] nvarchar(50) NULL,
	[Categoria] nvarchar(50) NULL,
	[PrecioUnitario] real NULL,
	[Cantidad] int NULL,
	[Subtotal] real NULL
)
GO

CREATE TABLE [Formapago]
(
	[FormapagoID] int NOT NULL IDENTITY (1, 1),
	[Yape] nvarchar(50) NULL,
	[Tarjeta] nvarchar(50) NULL,
	[Efectivo] nvarchar(50) NULL
)
GO

CREATE TABLE [Metodopago]
(
	[MetodopagoID] int NOT NULL IDENTITY (1, 1),
	[Yape] nvarchar(50) NULL,
	[Tarjeta] nvarchar(50) NULL,
	[Efectivo] nvarchar(50) NULL
)
GO

CREATE TABLE [Ordencompra]
(
	[OrdencompraID] int NOT NULL IDENTITY (1, 1),
	[FormapagoID] int NOT NULL,
	[ProveedorID] int NOT NULL,
	[RequerimientoID] int NOT NULL,
	[Categoria] nvarchar(50) NULL,
	[CostoTotal] real NULL,
	[Fecha] date NULL
)
GO

CREATE TABLE [Producto]
(
	[ProductoID] int NOT NULL IDENTITY (1, 1),
	[CategoriaID] int NOT NULL,
	[Nombre] nvarchar(50) NULL,
	[Descripcion] nvarchar(50) NULL,
	[Stock] nvarchar(50) NULL,
	[FechaVencimiento] date NULL
)
GO

CREATE TABLE [Proveedor]
(
	[ProveedorID] int NOT NULL IDENTITY (1, 1),
	[CiudadID] int NOT NULL,
	[Ruc] nvarchar(50) NULL,
	[Nombre] nvarchar(50) NULL,
	[RazSocial] nvarchar(50) NULL,
	[Telefono] nvarchar(50) NULL,
	[Direccion] nvarchar(50) NULL,
	[Estado] bit NULL
)
GO

CREATE TABLE [Requerimiento]
(
	[RequerimientoID] int NOT NULL IDENTITY (1, 1),
	[ProductoID] int NOT NULL,
	[Descripcion] nvarchar(50) NULL,
	[Cantidad] int NULL,
	[PrecioUnitario] int NULL,
	[SubTotal] real NULL
)
GO

CREATE TABLE [Venta]
(
	[VentaID] int NOT NULL IDENTITY (1, 1),
	[ClienteID] int NOT NULL,
	[CierrecajaID] int NOT NULL,
	[NombreProducto] nvarchar(50) NULL,
	[Categoria] nvarchar(50) NULL,
	[PrecioUnitario] nvarchar(50) NULL,
	[Cantidad] int NULL,
	[Stock] int NULL,
	[FechaVencimiento] date NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Capital] 
 ADD CONSTRAINT [PK_Capital]
	PRIMARY KEY CLUSTERED ([CapitalID] ASC)
GO

ALTER TABLE [Categoria] 
 ADD CONSTRAINT [PK_Categoria]
	PRIMARY KEY CLUSTERED ([CategoriaID] ASC)
GO

ALTER TABLE [Cierrecaja] 
 ADD CONSTRAINT [PK_Cierrecaja]
	PRIMARY KEY CLUSTERED ([CierrecajaID] ASC)
GO

ALTER TABLE [Ciudad] 
 ADD CONSTRAINT [PK_Ciudad]
	PRIMARY KEY CLUSTERED ([CiudadID] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([ClienteID] ASC)
GO

ALTER TABLE [Detalleordencompra] 
 ADD CONSTRAINT [PK_Detalleordencompra]
	PRIMARY KEY CLUSTERED ([DetalleordencompraID] ASC)
GO

ALTER TABLE [Detallepedido] 
 ADD CONSTRAINT [PK_Detallepedido]
	PRIMARY KEY CLUSTERED ([DetallepedidoID] ASC)
GO

ALTER TABLE [Formapago] 
 ADD CONSTRAINT [PK_Formapago]
	PRIMARY KEY CLUSTERED ([FormapagoID] ASC)
GO

ALTER TABLE [Metodopago] 
 ADD CONSTRAINT [PK_Metodopago]
	PRIMARY KEY CLUSTERED ([MetodopagoID] ASC)
GO

ALTER TABLE [Ordencompra] 
 ADD CONSTRAINT [PK_Ordencompra]
	PRIMARY KEY CLUSTERED ([OrdencompraID] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([ProductoID] ASC)
GO

ALTER TABLE [Proveedor] 
 ADD CONSTRAINT [PK_Proveedor]
	PRIMARY KEY CLUSTERED ([ProveedorID] ASC)
GO

ALTER TABLE [Requerimiento] 
 ADD CONSTRAINT [PK_Requerimiento]
	PRIMARY KEY CLUSTERED ([RequerimientoID] ASC)
GO

ALTER TABLE [Venta] 
 ADD CONSTRAINT [PK_Venta]
	PRIMARY KEY CLUSTERED ([VentaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Venta_Cierrecaja] 
 ON [Venta] ([CierrecajaID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cierrecaja] ADD CONSTRAINT [FK_Cierrecaja_Capital]
	FOREIGN KEY ([CapitalID]) REFERENCES [Capital] ([CapitalID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Metodopago]
	FOREIGN KEY ([MetodopagoID]) REFERENCES [Metodopago] ([MetodopagoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detalleordencompra] ADD CONSTRAINT [FK_Detalleordencompra_Ordencompra]
	FOREIGN KEY ([OrdencompraID]) REFERENCES [Ordencompra] ([OrdencompraID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detalleordencompra] ADD CONSTRAINT [FK_Detalleordencompra_Producto]
	FOREIGN KEY ([ProductoID]) REFERENCES [Producto] ([ProductoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallepedido] ADD CONSTRAINT [FK_Detallepedido_Venta]
	FOREIGN KEY ([VentaID]) REFERENCES [Venta] ([VentaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Detallepedido] ADD CONSTRAINT [FK_Detallepedido_Producto]
	FOREIGN KEY ([ProductoID]) REFERENCES [Producto] ([ProductoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordencompra] ADD CONSTRAINT [FK_Ordencompra_Formapago]
	FOREIGN KEY ([FormapagoID]) REFERENCES [Formapago] ([FormapagoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordencompra] ADD CONSTRAINT [FK_Ordencompra_Requerimiento]
	FOREIGN KEY ([RequerimientoID]) REFERENCES [Requerimiento] ([RequerimientoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordencompra] ADD CONSTRAINT [FK_Ordencompra_Proveedor]
	FOREIGN KEY ([ProveedorID]) REFERENCES [Proveedor] ([ProveedorID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_Categoria]
	FOREIGN KEY ([CategoriaID]) REFERENCES [Categoria] ([CategoriaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Proveedor] ADD CONSTRAINT [FK_Proveedor_Ciudad]
	FOREIGN KEY ([CiudadID]) REFERENCES [Ciudad] ([CiudadID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Requerimiento] ADD CONSTRAINT [FK_Requerimiento_Producto]
	FOREIGN KEY ([ProductoID]) REFERENCES [Producto] ([ProductoID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Venta] ADD CONSTRAINT [FK_Venta_Cierrecaja]
	FOREIGN KEY ([CierrecajaID]) REFERENCES [Cierrecaja] ([CierrecajaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Venta] ADD CONSTRAINT [FK_Venta_Cliente]
	FOREIGN KEY ([ClienteID]) REFERENCES [Cliente] ([ClienteID]) ON DELETE No Action ON UPDATE No Action
GO
